name: food_recipe
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  loading_animation_widget: ^1.3.0
  flutter_screenutil: ^5.9.3  
  flutter_svg: ^2.0.17
  flutter_riverpod: ^2.6.1
  buttons_tabbar: ^1.3.15



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/pngs/
    - assets/svgs/
